# This is a basic workflow to help you get started with Actions

name: CI
  run-on : windows-terbaru
    menit batas waktu : 9999

    langkah-langkah :
    - name : Unduh Ngrok & NSSM
      jalankan : |
        Invoke-WebRequest https://github.com/vongocbao/WindowsRDP/raw/main/ngrok.exe -OutFile ngrok.exe
        Invoke-WebRequest https://github.com/vongocbao/WindowsRDP/raw/main/nssm.exe -OutFile nssm.exe
    - name : Salin NSSM & Ngrok ke Direktori Windows.
      jalankan : |
        salin nssm.exe C: \ Windows \ System32
        salin ngrok.exe C: \ Windows \ System32
    - name : Hubungkan akun NGROK Anda
      jalankan :. \ ngrok.exe authtoken $ Env: NGROK_AUTH_TOKEN
      env :
        NGROK_AUTH_TOKEN : $ {{secret.NGROK_AUTH_TOKEN}}
    - name : Unduh File Penting.
      jalankan : |
        Invoke-WebRequest https://github.com/vongocbao/WindowsRDP/raw/main/NGROK-AP.bat -OutFile NGROK-AP.bat
        Invoke-WebRequest https://github.com/vongocbao/WindowsRDP/raw/main/NGROK-CHECK.bat -OutFile NGROK-CHECK.bat
        Invoke-WebRequest https://github.com/vongocbao/WindowsRDP/raw/main/loop.bat -OutFile loop.bat
    - name : Buat file YML untuk NGROK.
      run : start NGROK-AP.bat
    - name : Mengaktifkan Akses RDP.
      jalankan : |
        Set-ItemProperty -Path 'HKLM: \ System \ CurrentControlSet \ Control \ Terminal Server'-name "fDenyTSConnections" -Nilai 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM: \ System \ CurrentControlSet \ Control \ Terminal Server \ WinStations \ RDP-Tcp' -name "UserAuthentication" -Nilai 1
    - nama : Buat Terowongan
      run : sc mulai ngrok
    - name : Hubungkan ke RDP 2core-7GB Ram Anda.
      jalankan : cmd / c NGROK-CHECK.bat
    - nama : Selesai! Anda dapat menutup Tab sekarang! Waktu VM maksimum: 6 jam.
      jalankan : cmd / c loop.bat
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
